name: Python code

on: [push]


jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkpoint@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: python3 main.py