# File: .github/workflows/hello.yml
name: Hello World

on: [push]  # triggers when you push to GitHub

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"
